### ISSUE TITLE
Parameterized limit throws an error

### ISSUE THREAD

**Issue by GergelyKalmar** [aws/amazon-redshift-python-driver#24] opened 2021-03-05 15:34 UTC
## Driver version 
2.0.874

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.24019

## Client Operating System
Ubuntu 20.04

## Python version
3.8.5

## Table schema
The error should be reproducible on any non-system table.

## Problem description
1. Expected behaviour: Results are printed when a parameterized limit is used
2. Actual behaviour: An error is thrown
3. Error message/stack trace:
```
> python3 test.py
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    cursor.execute("SELECT id FROM mydb.accounts WHERE id = %s LIMIT %s", [1, 10])
  File ".../lib/python3.8/site-packages/redshift_connector/cursor.py", line 162, in execute
    self._c.execute(self, operation, args)
  File ".../lib/python3.8/site-packages/redshift_connector/core.py", line 1097, in execute
    self.handle_messages(cursor)
  File ".../lib/python3.8/site-packages/redshift_connector/core.py", line 1172, in handle_messages
    raise self.error
redshift_connector.error.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': 'Not implemented', 'D': "\n  -----------------------------------------------\n  error:  Not implemented\n  code:      1001\n  context:   'IsA(cons, Const)' - \n  query:     527758\n  location:  pg_utils.cpp:5702\n  process:   padbmaster [pid=27215]\n  -----------------------------------------------\n", 'F': '/home/ec2-user/padb/src/sys/xen_execute.cpp', 'L': '9226', 'R': 'pg_throw'}
```
4. Any other details that can be helpful: the test code works when the limit parameter is hardcoded, that is, when the appropriate line is replaced with `cursor.execute("SELECT id FROM mydb.accounts WHERE id = %s LIMIT 10", [1])`.

## Python Driver trace logs
N/A

## Reproduction code
`test.py`:
```python
import os

import redshift_connector

conn = redshift_connector.connect(
    host=os.getenv("REDSHIFT_HOSTNAME"),
    database=os.getenv("REDSHIFT_DATABASE"),
    user=os.getenv("REDSHIFT_USERNAME"),
    password=os.getenv("REDSHIFT_PASSWORD"),
 )

cursor = conn.cursor()
cursor.execute("SELECT id FROM mydb.accounts WHERE id = %s LIMIT %s", [1, 10])
print(cursor.fetchall())
```

**Comment by Brooke-white** [comment] 2021-03-05 17:28
Hey @GergelyKalmar ,

Thanks for reaching out regarding this issue. The team will take a look into this and follow up shortly with findings.

**Comment by GergelyKalmar** [comment] 2021-03-05 17:55
One more note: I've quickly checked and it seems that parameterized `LIMIT` clauses work fine with the official `JDBC` driver.

**Comment by Brooke-white** [comment] 2021-03-15 16:58
Hi @GergelyKalmar ,

Using the following setup:
- `redshift_connector==2.0.876` 
- `Mac OS 10.15.7`
- `PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.24421`

I created some test users:
```sql
create user test_user1 with password DISABLE;
create user test_user2 with password DISABLE;
create user test_user3 with password DISABLE;
create user test_user4 with password DISABLE;
```

After executing the above statements, the relevant columns from my`pg_catalog.pg_users` are as follows:

|usename|usesysid|
|--------|-----|
|rdsdb|1|
|awsuser|100|
|test_user1|101|
|test_user2|102|
|test_user3|103|
|test_user4|104|

and executed the following Python script against the system table `pg_catalog.pg_users`:

```python
def test_github_issue_24_1(db_kwargs):
    with redshift_connector.connect(**db_kwargs) as con:
        cursor = con.cursor()
        cursor.execute("SELECT usename, usesysid FROM pg_catalog.pg_user WHERE usesysid >= %s LIMIT %s", [100, 4])
        print(cursor.fetchall())
>>> (['awsuser', 100], ['test_user1', 101], ['test_user2', 102], ['test_user3', 103])

def test_github_issue_24_2(db_kwargs):
    with redshift_connector.connect(**db_kwargs) as con:
        cursor = con.cursor()
        cursor.execute("SELECT usename, usesysid FROM pg_catalog.pg_user WHERE usesysid = %s LIMIT %s", [100, 4])
        print(cursor.fetchall())
>>> (['awsuser', 100],)

def test_github_issue_24_3(db_kwargs):
    with redshift_connector.connect(**db_kwargs) as con:
        cursor = con.cursor()
        cursor.execute("SELECT usename, usesysid FROM pg_catalog.pg_user WHERE usesysid = %s LIMIT %s", [1, 10])
        print(cursor.fetchall())
>>> (['rdsdb', 1],)
```

While the test I performed above has differences to yours, such as the table used, the filter and limit are applied without issue.


If you perform this test, do you see the same error? If so, I would recommend upgrading your cluster to use the latest version. See [here](https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-clusters.html#rs-maintenance-windows) for instructions from the AWS docs on how to do this. 

If you continue to experience issues using `FILTER` we can continue to investigate the root cause of this issue.

**Comment by GergelyKalmar** [comment] 2021-03-15 18:41
Hi @Brooke-white,

I have also noticed that the query works when executed against system tables, it does not work however when executed against other (regular) tables. Can you try to create a new table in a regular schema and see if you can reproduce the issue then?

**Comment by Brooke-white** [comment] 2021-03-15 20:45
Hey @GergelyKalmar ,

Apologies for the confusion, when using a regular table I am able to reproduced the behavior you detailed above. I'll continue investigating this and provide an update with my findings shortly.

**Comment by Brooke-white** [comment] 2021-04-05 19:43
Hi @GergelyKalmar ,

This issue can be resolved by passing the parameter for the limit clause as a string. For example

```python
with conn.cursor() as cursor:
    cursor.execute("create table x (c1 int)")
    cursor.execute("insert into x (c1) values (1), (2), (3)")

    # throws an error
    # cursor.execute("select c1 from x limit %s", [1])

    # either format executes successfully
    for param_option in ((2, '1'), ('2', '1')):
        cursor.execute("select c1 from x where c1 >= %s  limit %s ", param_option)
        print(cursor.fetchall())
```

**Closed** 2021-04-05 19:51 UTC

**Comment by GergelyKalmar** [comment] 2021-04-07 08:58
Splendid, that seems to have worked! A little unexpected that a string would work but an int wouldn't.
