### ISSUE TITLE
Driver is unable to handle response from RedShift

### ISSUE THREAD

**Issue by zaibacu** [aws/amazon-redshift-python-driver#157] opened 2023-05-04 14:03 UTC
## Driver version
2.0.903

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.49676

## Client Operating System
AWS Lambda (Amazon Linux)

## Python version
3.10

## Table schema
_Doesn't matter_

## Problem description
Getting `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 122: invalid start byte` when simply connecting to RedShift. **THIS IS VERY RARE OCCURENCE**, in our case - 7 times out of 5000 invocations. I'm guessing, that RedShift is too busy and driver is unable to handle such event

## Python Driver trace logs
```
  self.connection = self.engine.connect()
  File "/var/task/sqlalchemy/engine/base.py", line 3204, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/var/task/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/var/task/sqlalchemy/engine/base.py", line 3283, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/var/task/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/var/task/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/var/task/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/var/task/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/var/task/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/var/task/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/var/task/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/var/task/sqlalchemy/pool/base.py", line 677, in __connect
    pool.dispatch.connect.for_modify(
  File "/var/task/sqlalchemy/event/attr.py", line 329, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/var/task/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/var/task/sqlalchemy/util/langhelpers.py", line 1691, in go
    return once_fn(*arg, **kw)
  File "/var/task/sqlalchemy/engine/create.py", line 686, in first_connect
    dialect.initialize(c)
  File "/var/task/sqlalchemy/dialects/postgresql/base.py", line 3241, in initialize
    super(PGDialect, self).initialize(connection)
  File "/var/task/sqlalchemy/engine/default.py", line 407, in initialize
    self.server_version_info = self._get_server_version_info(
  File "/var/task/sqlalchemy/dialects/postgresql/base.py", line 3487, in _get_server_version_info
    v = connection.exec_driver_sql("select pg_catalog.version()").scalar()
  File "/var/task/sqlalchemy/engine/base.py", line 1669, in exec_driver_sql
    return self._exec_driver_sql(
  File "/var/task/sqlalchemy/engine/base.py", line 1578, in _exec_driver_sql
    ret = self._execute_context(
  File "/var/task/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/var/task/sqlalchemy/engine/base.py", line 2030, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/var/task/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/var/task/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/var/task/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/var/task/redshift_connector/cursor.py", line 211, in execute
    self._c.execute(self, operation, args)
  File "/var/task/redshift_connector/core.py", line 1279, in execute
    self.handle_messages(cursor)
  File "/var/task/redshift_connector/core.py", line 1359, in handle_messages
    self.message_types[code](self._read(data_len - 4), cursor)
  File "/var/task/redshift_connector/core.py", line 1350, in handle_DATA_ROW
    row.append(desc[0](data, data_idx, vlen))
  File "/var/task/redshift_connector/utils/type_utils.py", line 131, in text_recv
    return str(data[offset : offset + length], _client_encoding)
```

**Comment by Brooke-white** [comment] 2023-05-04 18:46
Hey @zaibacu, just to confirm this is occurring when using Redshift provisioned i.e. not Redshift serverless?

> I'm guessing, that RedShift is too busy and driver is unable to handle such event
this is my guess here as well. without access to server side (Redshift) logs we have limited insight here. 

I'd recommend some combination of the following
- reaching out to AWS support so internal analysis of server logs can be performed to determine the root cause of the failure to connect. Please provide them with this GitHub issue as a reference.
- use of sqlalchemy's connection pooling/some sort of re-try logic to recreate establishing the connection in these rare cases

**Comment by zaibacu** [comment] 2023-05-04 19:32
Hello, yes this is provisioned RedShift instance

**Comment by deichrenner** [comment] 2023-05-30 12:01
Hi @zaibacu,
We face the same issue on a provisioned RedShift instance but with much higher frequency of occurrence. 
Did you have any success yet on mitigating the issue?

**Comment by deichrenner** [comment] 2023-05-30 12:10
Thanks for getting back this quickly. We'll investigate if something along the lines of https://stackoverflow.com/a/53300049 would help to reduce the pain until the issue is resolved from AWS side.

30.05.2023 14:03:25 Šarūnas Navickas ***@***.***>:

**Comment by zaibacu** [comment] 2023-05-30 12:12
Yes, we have retry mechanism as well. Usually query works in 1-2 retry attempts

**Comment by NelsonAndrew** [comment] 2023-06-01 16:50
We have also began to experience this non-utf-8 response from redshift during connection initialization somewhat frequently.  Has anyone gotten a response from Amazon regarding the cause?  Can this be handled better by the driver?

**Comment by zaibacu** [comment] 2023-06-08 06:53
> We have also began to experience this non-utf-8 response from redshift during connection initialization somewhat frequently. Has anyone gotten a response from Amazon regarding the cause? Can this be handled better by the driver?

It seems to be this concrete driver issue and started after RedShift version bump (not every one gets update at the same time, that's why others encounter bug later). 

We are connecting to the same database in other project via JDBC driver. No problems are occuring there

**Comment by nsanor** [comment] 2023-06-19 13:33
> > We have also began to experience this non-utf-8 response from redshift during connection initialization somewhat frequently. Has anyone gotten a response from Amazon regarding the cause? Can this be handled better by the driver?
> 
> It seems to be this concrete driver issue and started after RedShift version bump (not every one gets update at the same time, that's why others encounter bug later).
> 
> We are connecting to the same database in other project via JDBC driver. No problems are occuring there

We are experiencing this issue as well. We have multiple data pipeline jobs that had not failed for months that all of a sudden started failing intermittently directly after a weekly maintenance patch was applied. 

Is there any update on this ticket? If not, is there any known workaround we can explore?

**Comment by zaibacu** [comment] 2023-06-19 16:19
> > > We have also began to experience this non-utf-8 response from redshift during connection initialization somewhat frequently. Has anyone gotten a response from Amazon regarding the cause? Can this be handled better by the driver?
> 
> > 
> 
> > It seems to be this concrete driver issue and started after RedShift version bump (not every one gets update at the same time, that's why others encounter bug later).
> 
> > 
> 
> > We are connecting to the same database in other project via JDBC driver. No problems are occuring there
> 
> 
> 
> We are experiencing this issue as well. We have multiple data pipeline jobs that had not failed for months that all of a sudden started failing intermittently directly after a weekly maintenance patch was applied. 
> 
> 
> 
> Is there any update on this ticket? If not, is there any known workaround we can explore?

No update, easiest workaround - create retry logic. It usually works from 2nd-3rd try. Poor man's solution, but have nothing better at the moment

**Comment by Brooke-white** [comment] 2023-06-20 19:57
Hi folks, apologies for the delay in updates. This issue is being investigated internally and updates will be provided as available. Until resolution is found, retry logic is our best suggestion, as folks mentioned above.

**Comment by tatiana** [comment] 2023-06-27 14:19
We also noticed this issue in the github.com/astronomer/astro-sdk project, we'll be trying to retry as well and wait for a more definite solution (https://github.com/astronomer/astro-sdk/issues/1976)

**Comment by deichrenner** [comment] 2023-07-04 09:00
Any news on this? The frequency of occurrence gets higher and higher and the implementation of retries is partly unfeasible in our codebase.  
Did anybody succeed in using a connection pool for fixing this (which was the advice by AWS support folks).

**Comment by Brooke-white** [comment] 2023-07-05 16:22
Hi folks, no major updates aside from a general recommendation to ensure your Redshift instance is running the latest cluster version. Please check [this page](https://docs.aws.amazon.com/redshift/latest/mgmt/cluster-versions.html) to see the latest cluster versions.

**Comment by Brooke-white** [comment] 2023-07-12 17:04
Hi folks, I have more of an update to provide. tl;dr: Redshift server team is investigating this issue. Sqlalchemy appears to trigger some potential server issue.

I was able to reproduce this issue using the following cluster:
Redshift 1.0.52931
DC2 Large Single Node

sqlalchemy does not need to be involved to reproduce the issue, though there is a clear pattern of sqlalchemy users encountering this behavior as sqlalchemy's postgres dialect (which sqlalchemy-redshift is built upon) issues a `select version()` query upon initialization, which results in this issue being surfaced.

this issue can be reproduced with redshift-connector alone as I believe there is some additional data being sent to redshift_connector which causes this issue.

Below is a script that reproduces the issue.

```python
import redshift_connector

with redshift_connector.connect(
    user='awsuser',
    host='xxx',
    password='xxx',
    database='dev',
    client_protocol_version=1,
    ssl=False,
    port =5439,
) as conn:
    with conn.cursor() as cursor:
        query="select version();"
        for _ in range(10):
            cursor.execute(query)
            print(query, cursor.fetchone())
```

After a non-deterministic number of query executions, (typically between 1 and 3), the code fails with exception. The exception is raised by redshift_connector due to an error in processing the DATA ROW returned by the query `select version()`.

When inspecting data over wire using wireshark I performed an analysis using postgres wire protocol docs for reference https://www.postgresql.org/docs/8.0/protocol-message-formats.html. 

```
-- Python Driver "select version() Data Row"--
0000   02 00 00 00 45 00 00 c6 0d 4a 40 00 ec 06 4a a5   ....E....J@...J.
0010   03 89 2d 7e 0a 8e fa ad 15 3f c7 47 c1 72 05 d7   ..-~.....?.G.r..
0020   f6 a8 f8 0c 80 18 00 6e 8b ed 00 00 01 01 08 0a   .......n........
0030   0b 9d f8 b7 fa b7 cc d1 44 00 00 00 85 00 01 00   ........D.......
0040   00 00 7b 50 6f 73 74 67 72 65 53 51 4c 20 38 2e   ..{PostgreSQL 8.
0050   30 2e 32 20 6f 6e 20 69 36 38 36 2d 70 63 2d 6c   0.2 on i686-pc-l
0060   69 6e 75 78 2d 67 6e 75 2c 20 63 6f 6d 70 69 6c   inux-gnu, compil
0070   65 64 20 62 79 20 47 43 43 20 67 63 63 20 28 47   ed by GCC gcc (G
0080   43 43 29 20 33 2e 34 2e 32 20 32 30 30 34 31 30   CC) 3.4.2 200410
0090   31 37 20 28 52 65 64 20 48 61 74 20 33 2e 34 2e   17 (Red Hat 3.4.
00a0   32 2d 36 2e 66 63 33 29 2c 20 52 65 64 73 68 69   2-6.fc3), Redshi
00b0   66 74 20 31 2e 30 2e 35 32 39 33 31 00 74 43 00   ft 1.0.52931.tC.
00c0   00 00 0b 53 45 4c 45 43 54 00                     ...SELECT.
```

```
44 => D (Data Row 'D' character)
00 00 00 85 => 133 (length of data row including length itself)
00 01 => 1 (there is one column)
00 00 00 7b => 123 (length of the column value in bytes SHOULD BE 121 as last 2 bytes are garbage)
50 6f 73 74 67 72 65 53 51 4c 20 38 2e
30 2e 32 20 6f 6e 20 69 36 38 36 2d 70 63 2d 6c
69 6e 75 78 2d 67 6e 75 2c 20 63 6f 6d 70 69 6c
65 64 20 62 79 20 47 43 43 20 67 63 63 20 28 47
43 43 29 20 33 2e 34 2e 32 20 32 30 30 34 31 30
31 37 20 28 52 65 64 20 48 61 74 20 33 2e 34 2e
32 2d 36 2e 66 63 33 29 2c 20 52 65 64 73 68 69 
66 74 20 31 2e 30 2e 35 32 39 33 31 00 74 => PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.52931�t (INCORRECT the last 2 bytes should be excluded)
```

this issue does not lead to deterministic exceptions in redshift_connector as sometimes these 2 spare bytes are utf-8 compatible e.g. 00 00, resulting in incorrect data but no failure.

I will continue tracking this issue and providing updates here available. Unfortunately, at this time I cannot provide any "nice" workaround to this issue aside from retry logic as has already been discussed.

**Comment by Brooke-white** [comment] 2023-07-20 16:22
Hi folks, a fix for this issue is anticipated in Redshift server P178

**Comment by MrCoffey** [comment] 2023-08-16 17:17
Hi, We managed to resolve this issue by upgrading our version of Amazon Redshit to [1.0.54899](https://docs.aws.amazon.com/redshift/latest/mgmt/cluster-versions.html).

**Comment by Brooke-white** [comment] 2023-08-16 17:40
Great to hear, thanks for the update, Jorge. Folks, if you're hitting this please upgrade your cluster to see resolution.

**Comment by Brooke-white** [comment] 2023-10-19 21:30
Redshift server P178 has been released. Please upgrade to the latest version of Redshift server to see resolution for this issue.

**Closed by Brooke-white** 2023-10-19 21:30 UTC
Labels: Redshift Server
