### ISSUE TITLE
Redshift query failing 

### ISSUE THREAD

**Issue by utkarsharma2** [aws/amazon-redshift-python-driver#167] opened 2023-06-09 16:07 UTC
## Driver version
redshift-connector 2.0.911

## Redshift version
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.51304

## Client Operating System
Ubuntu

## Python version
3.8

## Table schema
N/A we are tying to create schema

## Problem description
We suddenly observed below issue while running testcases:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 122: invalid start byte`

1. Expected behaviour: Query should work
3. Actual behaviour: Erroring out with error - UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 122: invalid start byte
4. Error message/stack trace:
```
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/engine/base.py:3320: in connect
    return self._connection_cls(self, close_with_result=close_with_result)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/engine/base.py:96: in __init__
    else engine.raw_connection()
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/engine/base.py:3399: in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/engine/base.py:3366: in _wrap_pool_connect
    return fn()
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/pool/base.py:327: in connect
    return _ConnectionFairy._checkout(self)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/pool/base.py:894: in _checkout
    fairy = _ConnectionRecord.checkout(pool)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/pool/base.py:493: in checkout
    rec = pool._do_get()
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/pool/impl.py:146: in _do_get
    self._dec_overflow()
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:70: in __exit__
    compat.raise_(
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/util/compat.py:211: in raise_
    raise exception
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/pool/impl.py:143: in _do_get
    return self._create_connection()
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/pool/base.py:273: in _create_connection
    return _ConnectionRecord(self)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/pool/base.py:388: in __init__
    self.__connect()
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/pool/base.py:702: in __connect
    pool.dispatch.connect.for_modify(
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/event/attr.py:320: in _exec_w_sync_on_first_run
    self(*args, **kw)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/event/attr.py:334: in __call__
    fn(*args, **kw)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py:1695: in go
    return once_fn(*arg, **kw)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/engine/create.py:670: in first_connect
    dialect.initialize(c)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py:3444: in initialize
    super(PGDialect, self).initialize(connection)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/engine/default.py:408: in initialize
    self.server_version_info = self._get_server_version_info(
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py:3690: in _get_server_version_info
    v = connection.exec_driver_sql("select pg_catalog.version()").scalar()
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1765: in exec_driver_sql
    return self._exec_driver_sql(
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1674: in _exec_driver_sql
    ret = self._execute_context(
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1948: in _execute_context
    self._handle_dbapi_exception(
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/engine/base.py:2133: in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/util/compat.py:211: in raise_
    raise exception
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/engine/base.py:1905: in _execute_context
    self.dialect.do_execute(
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/sqlalchemy/engine/default.py:736: in do_execute
    cursor.execute(statement, parameters)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/redshift_connector/cursor.py:240: in execute
    self._c.execute(self, operation, args)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/redshift_connector/core.py:1783: in execute
    self.handle_messages(cursor)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/redshift_connector/core.py:1966: in handle_messages
    self.message_types[code](self._read(data_len - 4), cursor)
.nox/test-3-8-airflow-2-6-0/lib/python3.8/site-packages/redshift_connector/core.py:1945: in handle_DATA_ROW
    row.append(desc[0](data, data_idx, vlen))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

data = b'\x00\x01\x00\x00\x00***PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.51304\x00\xa6'
offset = 6, length = 123

    def text_recv(data: bytes, offset: int, length: int) -> str:
>       return str(data[offset : offset + length], _client_encoding)
E       UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 122: invalid start byte
```
5. Any other details that can be helpful:
We observed that the same query works fine for `ra3.xlplus - gen3` but not for `dc2.large - gen2`

**Comment by Brooke-white** [comment] 2023-06-09 20:06
Hi @utkarsharma2,

thank you for opening this issue. this is an interesting behavior I have not seen before. could you please open a ticket with AWS support and provide this github issue as reference so the Redshift server team can investigate. thank you!

**Comment by deichrenner** [comment] 2023-06-12 11:33
This is most likely a duplicate of https://github.com/aws/amazon-redshift-python-driver/issues/157.

**Comment by Brooke-white** [comment] 2023-06-13 18:20
closing as this is a dupe of #157

**Closed by Brooke-white** 2023-06-13 18:20 UTC
