### ISSUE TITLE
improve UX of error message when connection is lost unexpectedly

### ISSUE THREAD

**Issue by dataders** [aws/amazon-redshift-python-driver#164] opened 2023-06-06 14:46 UTC
everything below is a paraphrase of @dbeatty10 in https://github.com/dbt-labs/dbt-redshift/issues/456#issuecomment-1570301047

### Root cause

When a network connection is lost unexpectedly, this driver's error message doesn't help the user realize it's really a network connection issue.

issues related to network connection are hard for end users to reproduce and introspect. fortunately we now have:
1. information now to fix the problem, and
2. more engineers (e.g. @jiezhen-chen and myself here at dbt Labs) to squash this issue once and for all!

### Solution

raise a better Exception just as `pg8000` has already implemented

### Background

Prior to Mar 27, 2021, the README of `pg8000` (predecessor to `redshift_connector`) [said](https://github.com/tlocke/pg8000/blob/c471e4dc64a631395960cfaad02983132bfa9b5a/README.adoc?plain=1#L1014-L1018):

> Occasionally, the network connection between `pg8000` and the server may go
>   down. If `pg8000` encounters a problem writing to a socket it raises
>   `BrokenPipeError: [Errno 32] Broken pipe`. If `pg8000` encounters a problem
>   reading from a socket it raises `struct.error: unpack_from requires a buffer
>   of at least 5 bytes`.

### Potential implementation

These commits in `pg8000` could be used as inspiration for how to catch this error within redshift_connector and re-raise it as a network error instead:
- https://github.com/tlocke/pg8000/commit/4b0a6c6734fd8483e9f15db4c5eac38937370a36
- https://github.com/tlocke/pg8000/commit/b167253ad9c133416d6b4a7b3fac96558d396c0b

### Related issues

Here's a listing of related issues across both redshift_connector and pg8000:

#### `pg8000`
  - https://github.com/tlocke/pg8000/issues/65
  - https://github.com/tlocke/pg8000/issues/98
  - https://github.com/tlocke/pg8000/issues/102

#### `redshift_connector`
  - https://github.com/aws/amazon-redshift-python-driver/issues/16
  - https://github.com/aws/amazon-redshift-python-driver/issues/96
  - https://github.com/aws/amazon-redshift-python-driver/issues/124
  - https://github.com/aws/amazon-redshift-python-driver/issues/142
#### `dbt-redshift`
  - https://github.com/dbt-labs/dbt-redshift/issues/456

**Comment by dataders** [comment] 2023-06-06 19:59
> Since the scope of the error message + logging improvements is well defined, I'll be marking this issue with "help wanted". If you or @jiezhen-chen would like to take on this issue you are more than welcome to.

can you tell me more about how your team uses the "help wanted" label?

**Comment by mrmarkfrench** [comment] 2023-06-23 20:15
To add a little bit of further insight from my own team's experience, we find that the driving factor appears to be a function of the total idle time over the lifetime of a connection. I'm not certain if this is related to a config value that might vary from one DB instance to another, but on our DB it appears that after 30 seconds of total cumulative idle time we get a broken pipe.

We are able to replicate this by several different mechanisms, but they boil down to the same thing:
1. If we request a large result and then take 30+ seconds to process that result, we find that the connection is broken when our process goes back to request the next batch of records to process.
2. If we request a small batch, process it quickly, and then request another, that works fine, but once the total processing time (with periodic queries between each batch throughout) reaches ~30 seconds, we get a broken pipe.
3. If we sleep for 10 seconds before each query, the first 3 queries succeed and the 4th fails on a broken pipe.
4. If we sleep for 5 seconds before each query, the first 6 queries succeed and the 7th fails on a broken pipe.

Our conclusion based on all of this is that it's the cumulative idle time on an open connection that seems to determine when we expect to see the connection fail.

**Comment by mrmarkfrench** [comment] 2023-06-23 20:18
Just to call it out, we don't find that the issue is how long a query runs for, but rather how long a connection is held open without an active query that causes the disconnect.

**Comment by mrmarkfrench** [comment] 2023-06-28 19:59
@Brooke-white some follow-up info:

1. We definitely have TCP keepalive enabled, and I can't find any difference in the configuration of the keepalive between systems where we experience this problem and ones where we do not.
2. The server reports that the connection was ended by the "peer", while the client does not log any kind of "I'm hanging up now" message, it goes straight from regular operation to complaining of a broken pipe. So as far as I can tell, both sides blame their counter-party.
3. Our network configuration does not allow me to open a telnet session from within this environment, so I'm not able to test this.
4. The client application is run in a Docker container, while the DB server is Amazon RDS. We don't see timeouts like this with connections to other DBs, so while that's definitely not proof positive that Docker isn't getting involved unhelpfully, it makes that explanation seem less likely.

**Comment by dbeatty10** [comment] 2023-08-07 23:14
It would be an improvement to raise an error like:
```
BrokenPipeError: Broken pipe, could not read data from client
```

or:
```
BrokenPipeError: Lost database connection
```

rather than the error it returns currently when the connection is lost:
```
unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)
```

**Comment by Brooke-white** [comment] 2023-09-19 16:20
fixed in 2.0.914

**Closed by Brooke-white** 2023-09-19 16:20 UTC
Labels: help wanted

**Comment by dbeatty10** [comment] 2023-09-19 16:28
Awesome news @Brooke-white !

Out of curiosity, what did you land on for the new error message?

**Comment by dbeatty10** [comment] 2023-09-19 16:42
@Brooke-white  Nevermind, found the new error messages within https://github.com/aws/amazon-redshift-python-driver/pull/185:

`InterfaceError`

```
BrokenPipe: server socket closed. We noticed a timeout is set for this connection. Consider raising the timeout or defaulting timeout to none.
```

```
BrokenPipe: server socket closed. Please check that client side networking configurations such as Proxies, firewalls, VPN, etc. are not affecting your network connection.
```
