### ISSUE TITLE
Cannon install with conda for python 3.8 & 3.9

### ISSUE THREAD

**Issue by kyri-petrou** [aws/amazon-redshift-python-driver#27] opened 2021-03-26 08:10 UTC
## Client Operating System
Ubuntu 20.04

## Python version
3.8 and 3.9

## Problem description
Cannot install with conda (conda-forge channel) in environments with python versions 3.8 and 3.9 (works with 3.6 and 3.7)

1. Expected behaviour:
To be able to install the package using conda

2. Actual behaviour:
Not able to install package using conda

3. Error message/stack trace:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
redshift_connector -> beautifulsoup4[version='>=4.7.0,<4.8.0'] -> python[version='>3.5|>=2.7,<3|>=3.6|>=2.7|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0']
redshift_connector -> python[version='>=3.5']
python=3.8
```
4. Any other details that can be helpful:
This issue also prevents installation of awswrangler 2.x

## Reproduction code
`conda create -n my_env -c conda-forge python=3.8 redshift_connector -y`

**Comment by Brooke-white** [comment] 2021-03-26 15:25
Hey @kyri-petrou ,

Thanks for reaching out regarding this issue. Could you share which version of `redshift_connector` you are using?

**Comment by Brooke-white** [comment] 2021-03-26 15:43
I've been able to reproduce this issue, a fix will be provided in the next release which is scheduled to occur this coming Monday March 29th.

**Comment by kyri-petrou** [comment] 2021-03-28 02:30
Okay thanks for the update! Glad I could be of help

**Comment by Brooke-white** [comment] 2021-03-29 23:10
Hi @kyri-petrou ,

Thank you for your patience. We've released a new version of `redshift_connector` that addresses this issue, `v2.0.877`. It is now available on conda. 

I have verified the issue is resolved by running the command you provided, `conda create -n my_env -c conda-forge python=3.8 redshift_connector -y`. Please reach out if you continue to experience this issue.

**Closed by Brooke-white** 2021-03-29 23:10 UTC
